spring:
  application:
    name: spring-boot-dubbo

dubbo:
  application:
    name: spring-boot-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.1.228:2181
